version: "3.9"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin123456
  myadmin:
    image: phpmyadmin
    ports:
      - "9090:80"
    links:
      - mysql:db
  web:
    build: .
    ports:
      - "45721:80"
    links:
      - mysql:db
