version: "3.9"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Sysadmin2021
    volumes:
      - "./wisptem.sql:/docker-entrypoint-initdb.d/2.sql"
  myadmin:
    image: phpmyadmin
    ports:
      - "9090:80"
    links:
      - mysql:db
  web:
    build: .
    ports:
      - "45721:80"
    links:
      - mysql:db
